"""HexaZero C FFI bindings for the Catan game engine."""

from .structs import (
    # Struct types
    Action,
    ActionRecord,
    Board,
    CatanMap,
    Coordinate,
    Game,
    LandTile,
    Port,
    RngState,
    SearchCtx,
    SearchResult,
    State,
    # Callback types
    DecideFn,
    ValueFn,
    # Dimension constants
    DEV_DECK_SIZE,
    MAX_ACTIONS,
    MAX_ADJ_TILES,
    MAX_COMPONENTS,
    MAX_DEGREE,
    MAX_DEV_DECK,
    MAX_PLAYERS,
    MAX_ROAD_EDGES,
    MAX_SEARCH_DEPTH,
    MT_N,
    NUM_DEV_TYPES,
    NUM_EDGES,
    NUM_LAND_TILES,
    NUM_NODES,
    NUM_PLAYER_STATE_FIELDS,
    NUM_PORTS,
    NUM_RESOURCES,
    TOTAL_NODES,
    TURNS_LIMIT,
    # Color enum
    COLOR_RED,
    COLOR_BLUE,
    COLOR_ORANGE,
    COLOR_WHITE,
    COLOR_NONE,
    # Resource enum
    RES_WOOD,
    RES_BRICK,
    RES_SHEEP,
    RES_WHEAT,
    RES_ORE,
    RES_NONE,
    # DevCardType enum
    DEV_KNIGHT,
    DEV_YEAR_OF_PLENTY,
    DEV_MONOPOLY,
    DEV_ROAD_BUILDING,
    DEV_VICTORY_POINT,
    DEV_NONE,
    # BuildingType enum
    BLD_SETTLEMENT,
    BLD_CITY,
    BLD_ROAD,
    # ActionType enum
    AT_ROLL,
    AT_MOVE_ROBBER,
    AT_DISCARD_RESOURCE,
    AT_BUILD_ROAD,
    AT_BUILD_SETTLEMENT,
    AT_BUILD_CITY,
    AT_BUY_DEVELOPMENT_CARD,
    AT_PLAY_KNIGHT_CARD,
    AT_PLAY_YEAR_OF_PLENTY,
    AT_PLAY_MONOPOLY,
    AT_PLAY_ROAD_BUILDING,
    AT_MARITIME_TRADE,
    AT_OFFER_TRADE,
    AT_ACCEPT_TRADE,
    AT_REJECT_TRADE,
    AT_CONFIRM_TRADE,
    AT_CANCEL_TRADE,
    AT_END_TURN,
    # ActionPrompt enum
    PROMPT_BUILD_INITIAL_SETTLEMENT,
    PROMPT_BUILD_INITIAL_ROAD,
    PROMPT_PLAY_TURN,
    PROMPT_DISCARD,
    PROMPT_MOVE_ROBBER,
    PROMPT_DECIDE_TRADE,
    PROMPT_DECIDE_ACCEPTEES,
    # Direction enum
    DIR_EAST,
    DIR_SOUTHEAST,
    DIR_SOUTHWEST,
    DIR_WEST,
    DIR_NORTHWEST,
    DIR_NORTHEAST,
    # NodeRef enum
    NREF_NORTH,
    NREF_NORTHEAST,
    NREF_SOUTHEAST,
    NREF_SOUTH,
    NREF_SOUTHWEST,
    NREF_NORTHWEST,
    # Player state field indices
    PS_VICTORY_POINTS,
    PS_ROADS_AVAILABLE,
    PS_SETTLEMENTS_AVAILABLE,
    PS_CITIES_AVAILABLE,
    PS_HAS_ROAD,
    PS_HAS_ARMY,
    PS_HAS_ROLLED,
    PS_HAS_PLAYED_DEV_CARD_IN_TURN,
    PS_ACTUAL_VICTORY_POINTS,
    PS_LONGEST_ROAD_LENGTH,
    PS_WOOD_IN_HAND,
    PS_BRICK_IN_HAND,
    PS_SHEEP_IN_HAND,
    PS_WHEAT_IN_HAND,
    PS_ORE_IN_HAND,
    PS_KNIGHT_IN_HAND,
    PS_PLAYED_KNIGHT,
    # Map type constants
    MAP_BASE,
    MAP_MINI,
    MAP_TOURNAMENT,
    NPLACE_OFFICIAL_SPIRAL,
    NPLACE_RANDOM,
)
from .build_lib import build
from .lib_loader import load_library
