"""HexaZero game interface — Pythonic wrapper around the C Catan engine."""

from hexzero.game.interface import CatanGame, StateView

from hexzero.bindings.structs import (
    Action,
    # Color constants
    COLOR_RED,
    COLOR_BLUE,
    COLOR_ORANGE,
    COLOR_WHITE,
    COLOR_NONE,
    # Action types
    AT_ROLL,
    AT_MOVE_ROBBER,
    AT_DISCARD_RESOURCE,
    AT_BUILD_ROAD,
    AT_BUILD_SETTLEMENT,
    AT_BUILD_CITY,
    AT_BUY_DEVELOPMENT_CARD,
    AT_PLAY_KNIGHT_CARD,
    AT_PLAY_YEAR_OF_PLENTY,
    AT_PLAY_MONOPOLY,
    AT_PLAY_ROAD_BUILDING,
    AT_MARITIME_TRADE,
    AT_OFFER_TRADE,
    AT_ACCEPT_TRADE,
    AT_REJECT_TRADE,
    AT_CONFIRM_TRADE,
    AT_CANCEL_TRADE,
    AT_END_TURN,
    # Prompt types
    PROMPT_BUILD_INITIAL_SETTLEMENT,
    PROMPT_BUILD_INITIAL_ROAD,
    PROMPT_PLAY_TURN,
    PROMPT_DISCARD,
    PROMPT_MOVE_ROBBER,
    PROMPT_DECIDE_TRADE,
    PROMPT_DECIDE_ACCEPTEES,
    # Resources
    RES_WOOD,
    RES_BRICK,
    RES_SHEEP,
    RES_WHEAT,
    RES_ORE,
    RES_NONE,
    # Building types
    BLD_SETTLEMENT,
    BLD_CITY,
    BLD_ROAD,
    # Engine limits
    MAX_PLAYERS,
    MAX_ACTIONS,
    TOTAL_NODES,
    MAX_DEGREE,
    NUM_RESOURCES,
    NUM_LAND_TILES,
    NUM_PLAYER_STATE_FIELDS,
)

__all__ = [
    "CatanGame",
    "StateView",
    "Action",
    # Colors
    "COLOR_RED",
    "COLOR_BLUE",
    "COLOR_ORANGE",
    "COLOR_WHITE",
    "COLOR_NONE",
    # Action types
    "AT_ROLL",
    "AT_MOVE_ROBBER",
    "AT_DISCARD_RESOURCE",
    "AT_BUILD_ROAD",
    "AT_BUILD_SETTLEMENT",
    "AT_BUILD_CITY",
    "AT_BUY_DEVELOPMENT_CARD",
    "AT_PLAY_KNIGHT_CARD",
    "AT_PLAY_YEAR_OF_PLENTY",
    "AT_PLAY_MONOPOLY",
    "AT_PLAY_ROAD_BUILDING",
    "AT_MARITIME_TRADE",
    "AT_OFFER_TRADE",
    "AT_ACCEPT_TRADE",
    "AT_REJECT_TRADE",
    "AT_CONFIRM_TRADE",
    "AT_CANCEL_TRADE",
    "AT_END_TURN",
    # Prompts
    "PROMPT_BUILD_INITIAL_SETTLEMENT",
    "PROMPT_BUILD_INITIAL_ROAD",
    "PROMPT_PLAY_TURN",
    "PROMPT_DISCARD",
    "PROMPT_MOVE_ROBBER",
    "PROMPT_DECIDE_TRADE",
    "PROMPT_DECIDE_ACCEPTEES",
    # Resources
    "RES_WOOD",
    "RES_BRICK",
    "RES_SHEEP",
    "RES_WHEAT",
    "RES_ORE",
    "RES_NONE",
    # Building types
    "BLD_SETTLEMENT",
    "BLD_CITY",
    "BLD_ROAD",
    # Limits
    "MAX_PLAYERS",
    "MAX_ACTIONS",
    "TOTAL_NODES",
    "MAX_DEGREE",
    "NUM_RESOURCES",
    "NUM_LAND_TILES",
    "NUM_PLAYER_STATE_FIELDS",
]
